# For more information: https://laravel.com/docs/sail
services:
  laravel.test:
    build:
      context: ./docker/8.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: sail-8.1/app
    ports:
      - '${APP_PORT:-8084}:80'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-8005}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
  phpmyadmin:
    networks:
      - sail
    image: 'phpmyadmin:5.2'
    ports:
      - '127.0.0.1:8080:80'
    environment:
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      PMA_HOST: mysql
  redis:
    image: 'redis:7-alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sailredis:/data'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
  meilisearch:
    image: 'getmeili/meilisearch:v1.6'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'sailmeilisearch:/data.ms'
    networks:
      - sail
  mailpit:
    image: 'axllent/mailpit:v1.20'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '127.0.0.1:${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
  sailmeilisearch:
    driver: local
